server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: ten
    password: 1q2w3e4r5t!
    hikari:
      connectionTimeout : 30000
      maximumPoolSize : 10
      maxLifetime : 1800000
      poolName : HikariCP
      readOnly : false
      connectionTestQuery : SELECT 1
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false



tenco:
  key: 746aeb7573278b4cad1dd5a85339eea0a6f4b86cf131ed5009d66880e33ce88ca88edcbaaafa128aff3f941b4bfa0b05c6caff25b9ef40983e6923205277d6c6      
      